/**:
  ros__parameters:
    debug: true
    show_pic: false


/camera_node:
    ros__parameters:
        videoflag: false
        video_path: "./Camera/new1.mp4"
        inner_shot_flag: false

/camera_info_node:
    ros__parameters:
        camera_matrix: [
            2045.7299044722633, 0, 639.91373901944,
            0, 2041.4000138988533, 505.5792498148916,
            0, 0, 1
        ]
        distortion: [
            -0.04513949433516694,
            -0.9392361285963754,
            -0.0017701462462787585,
            -0.0016870244604070346,
            8.479602455636757
        ]

/serial_node:
    ros__parameters:
        device_name: "/dev/ttyACM0"
        default_data_recv_mode: 114 # a:97 r:114
        default_data_recv_euler: [0.2, 0.0, 0.2]
        odom2shooter_r: 0.059 # odom to shooter ratio
        shooter2camera_tvec: [0.11, 0, 0.04]

/armor_detector_node:
    ros__parameters:
        binary_thres: 160
        gray_thres: 200
        contour_thres: 100
        enemy_color: 0 # 0-çº¢è‰²ï¼?1-è“è‰² 
        detect_mode: 0 # 0-æ™?é€šäºŒå€¼åŒ–ï¼?1-é€šé“ç›¸å‡äºŒå€¼åŒ– (int)

/rune_detector_node:
    ros__parameters:
        confidence_threshold: 0.95 #ç¥ç»ç½‘ç»œç½?ä¿¡åº¦é˜ˆå€?
        model_path: "/model/yolox_fp16.onnx" #è¿™é‡Œçš„è·¯å¾„æ˜¯ç›¸å?¹è·¯å¾?

/rune_tracker_node:
    ros__parameters:
        bullet_speed: 25.0
        filter_astring_threshold: 20 #ç”¨äºä¸å¯ç”¨æ•°æ?çš„è?¡æ•°ï¼Œå½“æ•°æ®çªå˜æ—¶å€™ï¼Œåˆ™è¿‡æ»¤ä¸€å®šæ•°ç›?çš„æ•°æ?ä¹‹åä¸¢å…¥ ukf
        chasedelay: 0.0
        phase_offset: 0.0 #//ç›¸ä½å·?è¡¥å¿ï¼Œç”¨äºè¡¥å¿è?‚æµ‹åˆ°çš„è§’é€Ÿåº¦å’Œæ»¤æ³¢åè§’é€Ÿåº¦çš„ç›¸ä½å·®

/armor_shooter:
    ros__parameters:
        gravity: 9.781
        mode: 115 # small:115 big:98 light:108
        k_of_small: 0.01903
        k_of_big: 0.000556
        k_of_light: 0.00053
        correction_of_y: -2.3899999999999997
        correction_of_z: -1.7899999999999991
        stop_error: 0.001
        velocity: 25  #é£æœºå­å¼¹çš„é€Ÿåº¦ä¸?30m/s
        number_of_iterations: 60
        yaw_threshold: 0.005
        pitch_threshold: 0.005

/rune_shooter:
    ros__parameters:
        gravity: 9.781
        mode: 115 # small:115 big:98 light:108
        k_of_small: 0.01903
        k_of_big: 0.000556
        k_of_light: 0.00053
        correction_of_y: -2.3899999999999997
        correction_of_z: -1.7899999999999991
        stop_error: 0.001
        velocity: 25
        number_of_iterations: 60
